imports:
  - {resource: '@TJMSySiteBundle/config/config.yml'}
  - {resource: ../../../config/symfony.yml}
  - {resource: ../../../config/protected.local.yml}

parameters:
    kernel.root_dir: !php/const TJM\SyWeb\APP_DIR

framework:
 assets: ~
 default_locale: '%locale%'
 http_method_override: true
 request:
  formats:
   # md: 'text/x-markdown'
   md: 'text/plain'
   xhtml: 'application/xhtml+xml'
 router:
  resource: '%kernel.root_dir%/config/routing.yml'
  strict_requirements: ~
 secret: '%secret%'
 #--enable session for security component's csrf token
 session:
   enabled: true
   #--make cookies more secure, via <https://symfony.com/doc/4.4/session.html>
   cookie_samesite: 'lax'
   cookie_secure: 'auto'
   #--use PHP's session storage
   handler_id: null
 trusted_hosts: ~

security:
 access_control:
  -
   path: '^%secure.path%/?login$'
   roles: IS_AUTHENTICATED_ANONYMOUSLY
  -
   path: '^%secure.path%'
   roles: ROLE_ADMIN
 encoders:
  Symfony\Component\Security\Core\User\User: '%secure.encoder%'
 firewalls:
  dev:
   pattern: ^/(_(profiler|wdt)|css|images|js)/
   provider: main
   security: false
  protected:
    anonymous: lazy
    form_login:
      check_path: 'protected_secure_login'
      csrf_token_generator: security.csrf.token_manager
      default_target_path: protected_secure
      login_path: 'protected_secure_login'
    logout:
     path: 'protected_secure_logout'
    pattern: '^%secure.path%'
    provider: protected
  main:
   anonymous: lazy
   provider: main
 providers:
  main:
   memory: ~
  protected:
   memory:
    users: '%secure.users%'

services:
 _defaults:
  autowire: true
 ProtectedApp\Controller\:
   resource: '%kernel.project_dir%/src/ProtectedApp/Controller'
   tags: ['controller.service_arguments']
tjm_sy_site:
 page_wraps:
  full: '@Protected/shells/full.{format}.twig'

twig:
 debug: "%kernel.debug%"
 paths:
   '%kernel.root_dir%/templates': 'Protected'
 strict_variables: "%kernel.debug%"
