imports:
  - {resource: '@TJMWikiSiteBundle/config/common-mark.yml'}
  - {resource: '@TJMWikiSiteBundle/config/converters.yml'}
  - {resource: '@TJMWikiSiteBundle/config/html-to-markdown.yml'}
services:
 _defaults:
  autoconfigure: true
  autowire: true
  bind:
   $env: '%kernel.environment%'
 ParsedownExtra:
   class: ParsedownExtra #-! required because not namespaced
 TJM\Wiki\Wiki:
   arguments:
      $opts:
        path: '%data_content.path%'
        eventDispatcher: '@event_dispatcher'
        fileSystemCaseInsensitvity: false
   calls:
      - addPlugin: ['@TJM\WikiSite\WikiSite']
      - addPlugin: ['@TJM\WikiBlog\Blog']
 TJM\WikiBlog\Blog:
   arguments:
      $site: '@TJM\WikiSite\WikiSite'
      $opts:
        maxCount: 50
        name: "Toby's Log"
 TJM\WikiSite\WikiSite:
    arguments:
      $opts:
        converters:
          - '@TJM\WikiSite\FormatConverter\HtmlToMarkdownConverter'
          - '@TJM\WikiSite\FormatConverter\MarkdownToCleanMarkdownConverter'
          - '@TJM\WikiSite\FormatConverter\MarkdownToHtmlConverter'
        name: "Toby Mackenzie's Site"
        router: '@router'
        shellTemplate: '@@Public/shells/full'
        twig: '@twig'
        viewRoute: 'public_wiki_page'
        viewTemplate: '@@Public/default/simplePage'
        #--set to hydrate, otherwise not instantiated
        wiki: '@TJM\Wiki\Wiki'
 ##==commands
 PublicApp\Command\:
   autowire: true
   autoconfigure: true
   resource: '%kernel.project_dir%/src/Command'
 ##==controllers
 PublicApp\Controller\:
   resource: '%kernel.project_dir%/src/Controller'
 ##==listeners
 app.headers_listener:
  class: PublicApp\Listener\HeadersListener
  arguments: ['%kernel.environment%', '%public.host%']
  tags:
   - {name: kernel.event_listener, event: kernel.response, priority: -129} #-# priority to prevent CSP stripping by https://github.com/symfony/symfony/pull/25532
 PublicApp\Listener\ViewContentListener:
  tags:
   - {name: kernel.event_listener, event: 'TJM\WikiSite\Event\ViewContentEvent'}
 PublicApp\Listener\ViewDataListener:
  arguments:
   - '@request_stack'
   - '@router'
   - '%tjm_sy_site.wraps%'
   - '%public.host%'
   - '%public.canonical_host%'
  public: true
  tags:
   - {name: kernel.event_listener, event: 'TJM\WikiSite\Event\ViewDataEvent'}
 ##==templates
 PublicApp\Twig\IncludeDataExtension:
   arguments: ['%data.path%']
 PublicApp\Twig\IncludeScriptExtension:
   arguments: ['%scripts.path%']
 templates:
   alias: twig
   public: true
